### ISSUE TITLE
Improve user access to long lists of segments in read-only mode

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#107] opened 2016-11-23 20:52 UTC
With the segment list shown in read-only mode, it is impossible to see (or click!) segments that are not showing up in the very small area allocated to the list.

@cpinter is it possible to make individual segments not editable, but make it possible to scroll down the list?

@che85 @cpinter we should not display the Segment Editor controls that are irrelevant in the read-only mode (see screenshot with the red square around the stuff that should not be shown)

![image](https://cloud.githubusercontent.com/assets/313942/20578317/c2273c7e-b194-11e6-9161-a4951692c01c.png)

**Comment by che85** [comment] 2016-11-23 20:54
I can simply hide them. Anyway I need to disable the buttons since the readonly mode only applies to the segments table

**Comment by cpinter** [comment] 2016-11-23 20:58
Good point, we should not show the effects section.

Isn't there a movable separator under the list that you can use to make it taller?

**Comment by fedorov** [comment] 2016-11-23 20:59
@cpinter indeed, there is, and it even changes mouse icon on mouse over, but it is disabled - I cannot move it :(

**Comment by che85** [comment] 2016-11-23 20:59
Do you really want it to become taller? What about setting a fixed height and just using the scroll?

**Comment by fedorov** [comment] 2016-11-23 20:59
scroll is disabled as well - that would definitely be a good solution

**Comment by cpinter** [comment] 2016-11-23 21:00
It depends a lot on your use case how tall you want it.

The table shouldn't be fully disabled like it shows on your screenshot. I'll look into this

**Comment by che85** [comment] 2016-11-23 21:01
@fedorov Are you working with my current PR? If not, please check it out. It might already fix this issue

**Comment by cpinter** [comment] 2016-11-23 21:02
The fix needs to ultimately be in Slicer core. I'll check this out once I finished what I'm working on right now

**Comment by fedorov** [comment] 2016-11-23 21:07
@che85 indeed, the segment selection is resolved, and jump to segment is also working now!! Great job! However, something else went wrong this time -- see below!

![image](https://cloud.githubusercontent.com/assets/313942/20578746/e428b418-b196-11e6-9ead-cfd40152a40b.png)

**Comment by fedorov** [comment] 2016-11-23 21:07
(and no, I did not photoshop that! :)

**Comment by che85** [comment] 2016-11-23 21:08
I had that issue too. Once I restarted Slicer it was ok. I probably happened, when I reloaded the module, but I am not sure. I will check this.

**Comment by che85** [comment] 2016-11-23 21:11
Does it always happen to you? I cannot reproduce this and I don't get any errors.

**Comment by fedorov** [comment] 2016-11-23 21:12
that was with a freshly started Slicer, but after restart, it didn't happen again! 

![image](https://cloud.githubusercontent.com/assets/313942/20578877/72f08b44-b197-11e6-9a36-0cc4dde6d9d9.png)

Looks like we cleared the Test dataset 2 from https://fedorov.gitbooks.io/rsna2016-qirr-dicom4qi/content/instructions/sr-tid1500.html!!! <hooray icon>

Terminology was populated correctly too, but it would be nice to add anatomic location to the tooltip. I will create a separate issue for Csaba consideration.

**Comment by che85** [comment] 2016-11-23 21:13
Very nice!

**Comment by cpinter** [comment] 2016-11-23 21:13
Anatomic region information is only shown in the tooltip if it's read and is valid. If reading or parsing is buggy then it should be fixed of course.

**Comment by fedorov** [comment] 2016-11-23 21:18
@cpinter you are right - it is the reading issue! Let me know if I need to create a separate issue. You should be able to reproduce with dataset 2 from this page: https://fedorov.gitbooks.io/rsna2016-qirr-dicom4qi/content/instructions/sr-tid1500.html

**Comment by cpinter** [comment] 2016-11-23 21:23
Up to you whether to create a new issue.

So in summary:
* Segments table in read-only segment editor is fully disabled, but should only be made read-only (I thought I implemented it this way but apparently something is off)
* Dataset 2 fails to read anatomical region properly

**Comment by fedorov** [comment] 2016-11-23 21:26
> Segments table in read-only segment editor is fully disabled, but should only be made read-only (I thought I implemented it this way but apparently something is off)

@che85 fixed this issue, it is resolved now. Here is how the interface looks like now:

![image](https://cloud.githubusercontent.com/assets/313942/20579214/88ac8a76-b199-11e6-9d86-5ffe0ed2c342.png)

> Dataset 2 fails to read anatomical region properly

Correct.

**Comment by cpinter** [comment] 2016-11-23 21:36
I can still hide the effects area in read-only state if you think it's better that way.

**Comment by fedorov** [comment] 2016-11-23 21:37
yes, definitely - I just wanted to say that the segment access is fixed

**Comment by che85** [comment] 2016-11-23 21:39
@cpinter Disabled should be:
- all buttons above the segments table
- undo/redo
- all effect buttons,
- masking/options groupboxes

**Comment by che85** [comment] 2016-11-23 21:39
Once you support that, I will remove all the code from Reporting...

**Comment by cpinter** [comment] 2016-11-23 21:41
I don't understand why it's needed to add super temporary workaround code in Reporting. It makes my job harder because the way it works after your workarounds does not reflect the state I need to fix.
Please just tell me what to fix instead

**Comment by fedorov** [comment] 2016-11-23 21:41
@che85 will you hide all those unnecessary UI elements from the widget, in Reporting?

**Comment by che85** [comment] 2016-11-23 21:42
I am doing this right now.

https://github.com/che85/Reporting/blob/newReporting/Py/Reporting.py#L607-L615

**Comment by fedorov** [comment] 2016-11-23 21:44
sorry, I guess there is mis-comminication.

@che85 are you saying read-only mode should be possible to specify using Segment Editor API, and if it is triggered, all those elements should be hidden?

@cpinter I am just not sure what you would like to support in Segment Editor, and what you don't plan to support. We are optimizing Reporting user experience, independently of the priorities for Segment Editor, so that's why we need those workarounds. I think that it might make sense to have "read only" mode that can be triggered via Segment Editor widget API, which would disable editing of segments, and hide all UI elements irrelevant for read only mode.

Hope this helps.

**Comment by che85** [comment] 2016-11-23 21:45
@cpinter I only added that code, because my Slicer build doesn't work and I don't know right now how to fix it and we/I don't have time to wait for a new nightly build. 

And it's really not much code for my workaround ...

@fedorov I am not talking about hiding them, I am talking about disabling those elements

**Comment by cpinter** [comment] 2016-11-23 21:46
Segment editor read-only mode solely exists because of your use case and I think because of this it should support it fully. When another use case for read-only appears then we can start customizing.

I'd strongly prefer not to chop the same tree from two sides, so I'll do the same in segment editor what Christian did in Reporting. That code can be removed any time, I'll commit in a matter of minutes.

I was just confused because in the screenshot the whole esgment table was disabled but I know I implemented it differently.

**Comment by che85** [comment] 2016-11-23 21:48
Sorry for the confusion 😊

**Comment by cpinter** [comment] 2016-11-23 21:49
No problem! Has your build problem been resolved since then?

**Comment by fedorov** [comment] 2016-11-23 21:50
> That code can be removed any time, I'll commit in a matter of minutes.

Right, but after you change it in a matter of minutes, @che85 will only be able to test/debug it on Friday, since he cannot build Slicer on his mac, and tomorrow is a holiday. 

To me it looks like for now we don't need any changes to the Slicer core. Let's revisit this after RSNA when the dust settles. Sorry for all these hectic communications. I did plan this project in advance, but multiple developments had to come together, and it didn't happen until very recently. In the end, it all seems to be working out nicely. Sorry for the confusion.

> I am doing this right now. https://github.com/che85/Reporting/blob/newReporting/Py/Reporting.py#L607-L615

@che85 the point is to hide the irrelevant elements in read-only mode, not just disable them. They have no use for the user.

**Comment by che85** [comment] 2016-11-23 21:51
@cpinter No honestly I stopped trying for now after two builds from scatch and reinstalling/making qt with brew. I might look into this after RSNA...

**Comment by cpinter** [comment] 2016-11-23 21:53
I think I'll commit anyway because it's already done, and it won't change anything for the user if the redundant calls in Reporting stay - unless there are objections.
It makes sense to disable all those components in the UI for read-only. I agree that the user shouldn't be able to choose effects and click undo/redo etc. when in read-only mode.

**Comment by cpinter** [comment] 2016-11-23 22:33
I'm looking at the dataset that has the anatomic region information. It's not a simple bug, it happens due to an assumption I made (added TODOs in the code about it but then forgot to ask).

The assumption was that there is one anatomic context loaded and that one is used in every case. But the region codes coming from the input segmentation are not found in that anatomic context, so it's invalid. What should happen when loading the anatomic context from the segmentation? A new one should be created?

**Comment by fedorov** [comment] 2016-11-23 22:39
Indeed, the assumption was not correct. I think it would be good to have it implemented the same way as in http://qiicr.org/dcmqi/#/seg - there is a separate selector for anatomic region context. And then at the time SEG is imported, a dynamic one is created as done for the category/type context. What do you think?

Sorry, I didn't think or discuss this topic clearly earlier. I hope it does not create too much trouble! Definitely this is not urgent and I don't expect it to be fixed before RSNA!

**Comment by cpinter** [comment] 2016-11-23 22:45
Implementing it should be pretty straightforward, I think I can do it tomorrow.

There is a combobox for anatomic context, and the logic is in place already. Hiding the combobox if there is only one loaded anatomic context is only a feature I added. So adding a new context for the SEG the same way a new terminology context is added will be no problem.

**Comment by cpinter** [comment] 2016-11-23 22:45
Now I'd like to ask for that separate issue if your offer still stands :) Thanks!

**Closed** 2016-11-23 23:08 UTC
Labels: enhancement
