### ISSUE TITLE
Change of the segment color does not have effect on the color used for painting

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#76] opened 2016-10-07 21:45 UTC
Steps to reproduce:
- add segment
- paint
- change color
- paint

![image](https://cloud.githubusercontent.com/assets/313942/19206264/a670bec8-8cb5-11e6-9adb-f66b29bda2b3.png)

As an aside, what is the expected behavior of Segment Editor when something was painted and then color changed - is color change supposed to propagate to the segment label that already exists? I would think it should.

**Comment by cpinter** [comment] 2016-10-11 21:19
I cannot reproduce this. If I change the color of a segment with the terminology selector, then the color of the segment changes immediately in the slice viewers, and if I do more painting it will be of that color.
I'll try it on Mac tomorrow.

**Comment by cpinter** [comment] 2016-10-12 17:36
Works fine on Mac too.

**Comment by cpinter** [comment] 2016-11-10 15:33
Can this be closed?

**Comment by lassoan** [comment] 2016-11-10 16:03
It is reproducible if you don't select terminology terms but just double-click on the color swatch.

**Comment by fedorov** [comment] 2016-11-14 19:40
Right, as Andras noted, this is reproducible if the color is updated using the color swatch inside the Terminology popup window.

**Comment by cpinter** [comment] 2016-11-17 14:28
I committed a fix, please check whenever convenient

**Comment by cpinter** [comment] 2016-11-17 14:28
It seems that my commit message closed this issue. I didn't expect that!

**Closed** 2016-11-17 14:28 UTC
Labels: bug, SlicerTerminology

**Comment by fedorov** [comment] 2016-11-17 18:01
@cpinter I've just tested, and it does look like the issue is fixed (so no need to reopen the issue!) - thank you!
